Repository gisaia/ARLAS-tagger, pull requests merged in 2019-11, with the labels that each got.

#48 Fix minor documentation issue
  docs/arlas-api-tagging.md
Labels: documentation, type:enhancement

#47 [Tagger] Generate API documentation
  release.sh
Labels: documentation

#51 Use slicing for Untag operation (fix #50)
  arlas-tagger-core/src/main/java/io/arlas/tagger/core/FilteredUpdater.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/UpdateServices.java
Labels: type:enhancement

#49 Endpoint for list of tagging jobs (fix #33)
  arlas-tagger-core/src/main/java/io/arlas/tagger/app/Documentation.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/app/KafkaConfiguration.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/kafka/TagKafkaConsumer.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/model/request/TagRefRequest.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/TagExploreService.java
  arlas-tagger-rest/src/main/java/io/arlas/tagger/rest/tag/TagStatusRESTService.java
  arlas-tagger/src/main/java/io/arlas/tagger/app/ArlasTagger.java
  conf/configuration.yaml
  docs/arlas-tagger-configuration.md
Labels: API, type:enhancement

#53 Rollback breaking change on status endpoint (fix #52)
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/UpdateServices.java
  arlas-tagger-rest/src/main/java/io/arlas/tagger/rest/tag/TagStatusRESTService.java
Labels: type:bug

#54 Renamed tag list endpoint
  arlas-tagger-rest/src/main/java/io/arlas/tagger/rest/tag/TagStatusRESTService.java
Labels: type:bug

#56 Fix -es parameter value
  release.sh
Labels: type:bug

#57 Added -rel parameter and SKIP_API option
  release.sh
Labels: type:enhancement

#59 Tag job list Kafka consumer problem
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/TagExploreService.java
Labels: type:bug

#60 Support new multigeometry syntax
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/TagRefService.java
  arlas-tagger-core/src/main/java/io/arlas/tagger/service/UpdateServices.java
  arlas-tagger/src/main/java/io/arlas/tagger/app/ArlasTagger.java
  docker/docker-files/docker-compose-arlas-server.yml
  pom.xml
  scripts/test-integration.sh
Labels: type:enhancement

#61 Add Authentication
  .travis.yml
  CONTRIBUTING.md
  arlas-tagger-core/src/main/java/io/arlas/tagger/app/ArlasTaggerConfiguration.java
  arlas-tagger-tests/src/test/java/io/arlas/tagger/rest/tag/TagAuthIT.java
  arlas-tagger-tests/src/test/resources/arlas-test.pem
  arlas-tagger/pom.xml
  arlas-tagger/src/main/java/io/arlas/tagger/app/ArlasTagger.java
  conf/configuration.yaml
  docker/docker-files/docker-compose.yml
  release.sh
  scripts/tests-integration-stage.sh
  scripts/tests-integration.sh
Labels: type:enhancement
